### ISSUE TITLE
Add site logo to customizer

### ISSUE THREAD

**Issue by pbwebdev** [CardanoPress/theme-bootstrap#1]
Users would like to use the base theme but have the option to add in a logo to the customizer of the base theme and not modify the code.

![image](https://user-images.githubusercontent.com/3688954/197433315-3ad255de-1de8-4e53-a538-2d54c41118f0.png)

Please add in the option for adding a site logo along with the site icon.

**Comment by kermage** [comment]
This you pointed is for the "favicon"; the help text says it 

```
Site Icons are what you see in browser tabs, bookmark bars, and within the WordPress mobile apps. Upload one here!
```

I added now the base custom logo feature but they'd still have to touch code eventually for their custom sizes if need be. https://github.com/CardanoPress/theme-bootstrap/commit/5634a7a4dad3a92211318e01e9ffcd12150fda4b

![image](https://user-images.githubusercontent.com/8350223/197442714-31e40487-0db9-4281-ac34-4f92ac03aaae.png)
